// packages/vue3/src/components/button/button.vue
<template>
  <button :class="cls">
    <slot></slot>
  </button>
</template>
<script setup lang="ts">
import { computed, defineProps } from 'vue';

const props = defineProps({
  type: {
    type: String,
    default: 'default',
  },
  block: {
    type: Boolean,
    default: false,
  },
  disabled: {
    type: Boolean,
    default: false,
  },
  outline: {
    type: Boolean,
    default: false,
  },
  round: {
    type: Boolean,
    default: false,
  },
  circle: {
    type: Boolean,
    default: false,
  },
  size: {
    type: String,
    default: '',
  },
});

const cls = computed(() => {
  return {
    btn: true,
    'btn-block': props.block,
    'btn-default': props.type === 'default',
    'btn-info': props.type === 'info',
    'btn-primary': props.type === 'primary',
    'btn-success': props.type === 'success',
    'btn-danger': props.type === 'danger',
    'btn-warning': props.type === 'warning',
    disabled: props.disabled,
    'btn-outline': props.outline,
    'btn-rounded': props.round,
    'btn-circle': props.circle,
    'btn-lg': props.size === 'large',
    'btn-sm': props.size === 'small',
    'btn-xs': props.size === 'mini',
  };
});
</script>
<style lang="scss" scoped>
@import '../../styles/button/index.scss';
</style>

// packages/react/src/Button/Button.tsx
import React, { forwardRef } from 'react';
import cs from '../_util/classNames';

import { BaseButtonProps } from './interface';

import './Button.scss';

const Button = forwardRef<null, BaseButtonProps>((props, ref) => {
  const {
    children,
    size,
    loading,
    className,
    type,
    shape,
    disabled,
    outline = false,
    block = false,
    onClick,
  } = props;
  const buttonRef = ref;

  const prefixCls = 'btn';
  const _type = type || 'default';
  const classNames = cs(
    prefixCls,
    `${prefixCls}-${_type}`,
    {
      [`${prefixCls}-block`]: block,
      // [`${prefixCls}-long`]: long,
      // [`${prefixCls}-status-${status}`]: status,
      // [`${prefixCls}-loading-fixed-width`]: loadingFixedWidth,
      [`${prefixCls}-loading`]: loading,
      // [`${prefixCls}-link`]: href,
      // [`${prefixCls}-icon-only`]: iconOnly || (!children && children !== 0 && iconNode),
      [`${prefixCls}-disabled`]: disabled,
      // [`${prefixCls}-rtl`]: rtl,
      [`${prefixCls}-outline`]: outline,
      [`${prefixCls}-rounded`]: shape == 'round',
      [`${prefixCls}-circle`]: shape == 'circle',
      [`${prefixCls}-lg`]: size === 'large',
      [`${prefixCls}-sm`]: size === 'small',
      [`${prefixCls}-xs`]: size === 'mini',
    },
    className,
  );

  const onInnerClick: React.MouseEventHandler<HTMLButtonElement> = (e: any) => {
    onClick && onClick(e);
  };

  return (
    <button ref={buttonRef} className={classNames} onClick={onInnerClick}>
      {children}
    </button>
  );
});

export default Button;
